### ISSUE TITLE
Compatibility with Rider 2020.3

### ISSUE THREAD

**Issue by mignatko** [Socolin/ApplicationInsightsRiderPlugin#2]
Will it be possible to see the plugin update for the newest version of Rider (2020.3) near soon?

**Comment by Socolin** [comment]
Hi,

It's supposed to be available since yesterday.

https://plugins.jetbrains.com/plugin/13984-application-insights-debug-log-viewer/versions/stable

Be sure to update in the plugins to the 1.0.11 (try restart Rider, I had to restart it, to get the update working).

If this does not works let me know

For the next times, I'm trying to build a version when rider release a new version each time, it may take few day for jetbrains to validate the plugins, but if I get the time there should be a build with the plugin in the github actions like this one:

https://github.com/Socolin/ApplicationInsightsRiderPlugin/actions/runs/412080734#artifacts

(Just extract the artifact then import from zip in rider)

**Comment by mignatko** [comment]
Hi, @Socolin, all works great now. Thanks for the fast response and for your work!
